# cli/lib/fragment.sh — Kconfig fragment tooling.
#
# Sourced by cli/kconform. A "fragment" is a file containing Kconfig
# assignments meant to be layered on top of a base defconfig via
# merge_config.sh (or `kconform fragment apply`, once that lands). Fragments
# are the idiomatic way to express "board X plus security hardening" or
# "board X plus debug-build extras" without duplicating the whole defconfig.
#
# This file ships the subset of fragment verbs that need no make:
#   - new <name>        — write a commented empty template
#   - lint <frag>       — validate syntax line-by-line
#
# `apply`, `diff`, and `new --from-diff` land in later revisions and will
# be implemented alongside the existing scratch-dir machinery used by L004
# and verify.

cmd_fragment() {
    if [ $# -eq 0 ]; then
        _kconform_fragment_usage
        return 0
    fi
    local sub="$1"
    shift
    case "$sub" in
        new)  _kconform_fragment_new "$@" ;;
        lint) _kconform_fragment_lint "$@" ;;
        apply|diff)
            echo "kconform fragment $sub: not implemented in this release" >&2
            echo "  Planned for a later version. See DESIGN §4.5." >&2
            return 2 ;;
        -h|--help|help) _kconform_fragment_usage ;;
        *)
            echo "kconform fragment: unknown sub-command '$sub'" >&2
            echo "  Sub-commands: new | lint | apply (pending) | diff (pending)" >&2
            return 2 ;;
    esac
}

_kconform_fragment_usage() {
    cat <<'EOF'
kconform fragment <sub-command> [args]

Sub-commands:
  new <name>              Write a commented empty fragment template to
                          <name>.cfg (or exactly <name> if it already ends
                          in .cfg / .fragment).

  lint <frag>             Validate fragment syntax. A valid fragment
                          contains only these line shapes:
                            (blank)
                            # <arbitrary comment>
                            CONFIG_X=y | =n | =m | =<int> | =<hex> | ="str"
                            # CONFIG_X is not set
                          Anything else — in particular `# CONFIG_X=y`, a
                          common pseudo-disable — is flagged.

  apply <frag> [<base>]   (pending) Merge <frag> into <base> via
                          merge_config.sh-equivalent, run olddefconfig,
                          report result.

  diff <f1> <f2>          (pending) Diff two fragments.

Run `kconform fragment <sub-command> --help` for per-sub-command details.
EOF
}

# --- fragment new ---------------------------------------------------------

_kconform_fragment_new() {
    local name=""
    local force=0
    while [ $# -gt 0 ]; do
        case "$1" in
            -f|--force) force=1; shift ;;
            -h|--help)
                cat <<'EOF'
kconform fragment new <name> [-f|--force]

Write a commented empty fragment template to <name>.cfg. If <name> already
ends in .cfg or .fragment the file is written at that literal path.

-f | --force    Overwrite an existing file.
EOF
                return 0 ;;
            --) shift; break ;;
            -*) echo "kconform fragment new: unknown flag '$1'" >&2; return 2 ;;
            *)
                if [ -z "$name" ]; then name="$1"
                else echo "kconform fragment new: unexpected arg '$1'" >&2; return 2
                fi; shift ;;
        esac
    done

    if [ -z "$name" ]; then
        echo "kconform fragment new: missing <name> argument" >&2
        return 2
    fi

    local path="$name"
    case "$name" in
        *.cfg|*.fragment) : ;;
        *) path="${name}.cfg" ;;
    esac

    if [ -e "$path" ] && [ "$force" != "1" ]; then
        echo "kconform fragment new: '$path' already exists (use --force to overwrite)" >&2
        return 2
    fi

    cat >"$path" <<'EOF'
# Kconfig fragment — generated by kconform fragment new.
#
# Layer this file on top of a base defconfig with either of:
#   scripts/kconfig/merge_config.sh configs/<board>_defconfig <this file>
#   kconform fragment apply <this file> configs/<board>_defconfig
#
# Syntax — use only these line shapes (replace <NAME> with a real symbol):
#   CONFIG_<NAME>=y                (enable a bool / tristate)
#   CONFIG_<NAME>=m                (enable a tristate as module)
#   CONFIG_<NAME>=<int>            (set an int symbol)
#   CONFIG_<NAME>=0x<hex>          (set a hex symbol)
#   CONFIG_<NAME>="string value"   (set a string symbol)
#   # CONFIG_<NAME> is not set     (canonical disable — note no '=')
#   # any plain comment            (documentation, free text)
#
# DO NOT write `# CONFIG_<NAME>=y` thinking it means "disable <NAME>" —
# Kconfig ignores that line entirely. Use `# CONFIG_<NAME> is not set`
# instead. (`kconform fragment lint` catches this mistake.)

# --- your assignments below ---
EOF

    echo "kconform fragment new: wrote '$path'"
}

# --- fragment lint --------------------------------------------------------

# Exit codes:
#   0  valid
#   1  one or more invalid lines
#   2  tool error (missing / unreadable file)
_kconform_fragment_lint() {
    local path=""
    local mode="text"
    while [ $# -gt 0 ]; do
        case "$1" in
            --json) mode="json"; shift ;;
            -h|--help)
                cat <<'EOF'
kconform fragment lint <frag> [--json]

Validate fragment syntax. Prints one finding per non-conforming line.

Exit codes:
  0  fragment is syntactically clean
  1  at least one invalid line
  2  file missing or unreadable
EOF
                return 0 ;;
            --) shift; break ;;
            -*) echo "kconform fragment lint: unknown flag '$1'" >&2; return 2 ;;
            *)
                if [ -z "$path" ]; then path="$1"
                else echo "kconform fragment lint: unexpected arg '$1'" >&2; return 2
                fi; shift ;;
        esac
    done

    if [ -z "$path" ]; then
        echo "kconform fragment lint: missing <frag> argument" >&2
        return 2
    fi
    if [ ! -f "$path" ]; then
        echo "kconform fragment lint: '$path': no such file" >&2
        return 2
    fi

    # Accumulate findings to a temp file so we can emit in chosen format.
    local tmp
    tmp="$(mktemp)"
    # shellcheck disable=SC2064
    trap "rm -f '$tmp'" RETURN

    local lineno=0
    local line
    while IFS= read -r line || [ -n "$line" ]; do
        lineno=$((lineno + 1))
        _kconform_fragment_classify "$line" "$lineno" >>"$tmp"
    done <"$path"

    local invalid_count
    invalid_count=$(grep -c '"severity":"error"' "$tmp" 2>/dev/null || true)
    invalid_count="${invalid_count:-0}"
    local total_lines=$lineno

    if [ "$mode" = "json" ]; then
        _kconform_fragment_emit_json "$tmp" "$path" "$invalid_count" "$total_lines"
    else
        _kconform_fragment_emit_text "$tmp" "$path" "$invalid_count" "$total_lines"
    fi

    if [ "$invalid_count" -gt 0 ]; then
        return 1
    fi
    return 0
}

# Classify a single line. On invalid lines, emits a JSON finding to stdout.
# On valid lines, emits nothing.
_kconform_fragment_classify() {
    local line="$1"
    local lineno="$2"

    # Blank.
    case "$line" in
        ''|[[:space:]]*) ;;
    esac
    local trimmed="${line#"${line%%[![:space:]]*}"}"
    trimmed="${trimmed%"${trimmed##*[![:space:]]}"}"
    if [ -z "$trimmed" ]; then
        return 0
    fi

    # Canonical disable: `# CONFIG_X is not set` (exactly — trailing text
    # other than optional trailing whitespace is an error).
    if [[ "$trimmed" =~ ^#[[:space:]]+CONFIG_[A-Za-z0-9_]+[[:space:]]+is[[:space:]]+not[[:space:]]+set$ ]]; then
        return 0
    fi

    # Pseudo-disable (`# CONFIG_X=...`) — invalid.
    if [[ "$trimmed" =~ ^#[[:space:]]+CONFIG_[A-Za-z0-9_]+= ]]; then
        local sym="${trimmed#\#}"
        sym="${sym#"${sym%%[![:space:]]*}"}"
        sym="${sym#CONFIG_}"
        sym="${sym%%=*}"
        printf '{"line":%d,"severity":"error","reason":"pseudo-disable","symbol":"CONFIG_%s","message":"`# CONFIG_X=...` is a plain comment; Kconfig ignores it. Use `# CONFIG_X is not set` to disable (no `=`)."}\n' "$lineno" "$sym"
        return 0
    fi

    # Plain comment.
    case "$trimmed" in
        \#*) return 0 ;;
    esac

    # Assignment: CONFIG_X=<value>
    if [[ "$trimmed" =~ ^CONFIG_[A-Za-z0-9_]+=.*$ ]]; then
        # Extract symbol and value. Minimal validation of the value — we
        # don't try to enforce type here since we don't know the Kconfig
        # type at fragment lint time. Just require that the symbol name is
        # a valid identifier (already enforced by regex above) and that
        # there's exactly one '=' before the value.
        local sym="${trimmed#CONFIG_}"
        sym="${sym%%=*}"
        case "$sym" in
            ''|[0-9]*)
                printf '{"line":%d,"severity":"error","reason":"bad-symbol","symbol":"CONFIG_%s","message":"symbol name must start with a letter or underscore"}\n' "$lineno" "$sym"
                return 0 ;;
        esac
        return 0
    fi

    # Anything else is unrecognized.
    local snippet="${trimmed:0:60}"
    # Strip double quotes from snippet so our JSON doesn't need escaping.
    snippet="${snippet//\"/\'}"
    snippet="${snippet//\\/\/}"
    printf '{"line":%d,"severity":"error","reason":"unrecognized","snippet":"%s","message":"line matches no valid fragment form (blank, comment, CONFIG_X=..., or `# CONFIG_X is not set`)"}\n' "$lineno" "$snippet"
}

_kconform_fragment_emit_text() {
    local tmp="$1"
    local path="$2"
    local invalid="$3"
    local total="$4"

    printf 'kconform fragment lint: %s\n' "$path"
    if [ "$invalid" -eq 0 ]; then
        printf '  clean — %d line(s) checked, 0 issues\n' "$total"
        return 0
    fi

    local line
    while IFS= read -r line; do
        [ -z "$line" ] && continue
        local lineno reason symbol snippet message
        lineno="$(printf '%s' "$line" | sed -n 's/.*"line":\([0-9]*\).*/\1/p')"
        reason="$(printf '%s' "$line"  | sed -n 's/.*"reason":"\([^"]*\)".*/\1/p')"
        symbol="$(printf '%s' "$line"  | sed -n 's/.*"symbol":"\([^"]*\)".*/\1/p')"
        snippet="$(printf '%s' "$line" | sed -n 's/.*"snippet":"\([^"]*\)".*/\1/p')"
        message="$(printf '%s' "$line" | sed -n 's/.*"message":"\([^"]*\)".*/\1/p')"

        local subject=""
        if [ -n "$symbol" ]; then subject="$symbol"
        elif [ -n "$snippet" ]; then subject="\"$snippet\""
        else subject="-"
        fi
        printf '  error line %s [%s] %s: %s\n' "$lineno" "$reason" "$subject" "$message"
    done <"$tmp"

    printf '  %d invalid line(s) out of %d total\n' "$invalid" "$total"
    return 0
}

_kconform_fragment_emit_json() {
    local tmp="$1"
    local path="$2"
    local invalid="$3"
    local total="$4"

    printf '{"file":"%s","total_lines":%d,"invalid_lines":%d,"findings":[' \
        "$(_kconform_fragment_json_escape "$path")" "$total" "$invalid"
    local first=1
    local line
    while IFS= read -r line; do
        [ -z "$line" ] && continue
        if [ $first -eq 0 ]; then printf ','; fi
        first=0
        printf '%s' "$line"
    done <"$tmp"
    printf ']}\n'
    return 0
}

_kconform_fragment_json_escape() {
    local s="$1"
    s="${s//\\/\\\\}"
    s="${s//\"/\\\"}"
    printf '%s' "$s"
}
